<?php
/** @var \Magento\Customer\Block\Account\Dashboard\Info $block */

if($block->getFieldValue() == '1') {
    $objectManager = \Magento\Framework\App\ObjectManager::getInstance();
    $customerSession = $objectManager->create('Magento\Customer\Model\Session');
    $id = $customerSession->getCustomer()->getId();
    $customer =    $objectManager->create('Magento\Customer\Model\Customer')->load($id);
    ?>
    <p><?= $block->escapeHtml(__('Nick Name:- '. $customer->getNickName())) ?></p>
<?php } ?>